# Generated by Django 3.2.5 on 2021-07-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
